### ISSUE TITLE
Mapa_Mental_Mayra

### ISSUE THREAD

**Issue by mayraglez917** [SistemasTecTlaxiaco/actividad-4-mapa-mental-mayraglez917#2]
[MAPA_MENTAL_MAYRA_GLEZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-mayraglez917/files/12689593/MAPA_MENTAL_MAYRA_GLEZ.pdf)
![CONJUNTOS, FUNCIONES Y RELACIONES  (2)](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-mayraglez917/assets/143307443/7b1024b2-8be7-479d-ab23-31e61963e3ac)

**Comment by 23620031** [comment]
MANEJO CONCEPTUAL Y DOMINIO DEL TEMA-> 25/25
RELACIÓN ENTRE LOS CONCEPTOS EN EL MAPA-> 25/25
CALIDAD DE LA PRESENTACIÓN-> 25/25
JERARQUIZACIÓN DE IDEAS-> 25/25

TOTAL=20/20

CALIFICADO POR EL EQUIPO DE LÓPEZ DOMÍNGUEZ

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
